### ISSUE TITLE
Datasets Release

### ISSUE THREAD

**Issue by seanzhuh** [ProvenceStar/PartGLEE#1]
Hi, thanks for your wonderful work, when do you plan to release the preprocessed datasets?

**Comment by ProvenceStar** [comment]
Hi, thank you for your interest in our work! We're happy to let you know that we have already open-sourced both the code and our refined dataset annotations. You're welcomed to use them, and we hope they will be helpful for your research!

> Hi, thanks for your wonderful work, when do you plan to release the preprocessed datasets?
