### ISSUE TITLE
Hierarchical SA-1B?

### ISSUE THREAD

**Issue by joshmyersdean** [ProvenceStar/PartGLEE#2]
Hello!

Thank you for this wonderful work! Super cool. 

I was wondering if you could point me towards the code needed to construct the hierarchical SA-1B data? I could not locate the `merge_sa1b.py` script referenced.

Thanks!
Josh

**Comment by ProvenceStar** [comment]
Hello Josh,

Thank you so much for your kind words and interest in our work!

Regarding your question, we handled the SA-1B data construction based on the approach referenced in GLEE. We have now uploaded the `merge_sa1b.py` script from GLEE, and we appreciate your reminder.

Please feel free to reach out if you have any further questions!

**Comment by joshmyersdean** [comment]
Thank you!
