### ISSUE TITLE
no datasets module in detectron2/data and projects/PartGLEE/partglee/data

### ISSUE THREAD

**Issue by kq-chen** [ProvenceStar/PartGLEE#3]
Thanks for your wonderful work! this helps me a lot!

I've encountered an issue while running the evaluation command. It seems that there is no `datasets` module in either `detectron2/data` directory or `projects/PartGLEE/partglee/data`. where can i get these files?
```bash
# python3 projects/PartGLEE/train_net.py --config-file projects/PartGLEE/configs/Inference/RN50/coco.yaml  --num-gpus 8 --eval-only

Traceback (most recent call last):
  File "/home/code/PartGLEE/projects/PartGLEE/train_net.py", line 19, in <module>
    from detectron2.data import MetadataCatalog
  File "/home/code/PartGLEE/detectron2/data/__init__.py", line 17, in <module>
    from . import datasets, samplers  # isort:skip
ImportError: cannot import name 'datasets' from partially initialized module 'detectron2.data' (most likely due to a circular import) (/home/code/PartGLEE/detectron2/data/__init__.py)
```

**Comment by ProvenceStar** [comment]
Thank you for your interest in our work, and we're glad to hear it has been helpful to you!

We apologize for the inconvenience. It seems that the previous version we uploaded was missing the required files. We've carefully reviewed and re-uploaded them, so the issue should now be resolved.

Please let us know if you encounter any further problems!

Best regards
